###
### Notes
###
### The travis web interface may choke silently and fail to
### update when there are issues with the .travis.yml file.
###
### The "travis-lint" command-line tool does not catch all
### errors which may lead to silent failure.
###
### Shell-style comments in this file must have "#" as the
### *first* character of the line.
###

###
### language
###

# travis-lint no longer permits this value
# language: emacs-lisp

###
### defining the build matrix
###
### ===>                                                       <===
### ===> each variation in env/matrix will be built and tested <===
### ===>                                                       <===
###
### variables under env/global are available to the build process
### but don't cause the creation of a separate variation
###

env:
  matrix:
#   - EMACS=xemacs21
#   - EMACS=emacs22 E: Package 'libtiff4:i386' has no installation candidate
#   - EMACS=emacs23 Cannot open load file: ert
#   - EMACS=emacs24 Symbol's function definition is void: let-when-compile
    - EMACS=emacs25
    - EMACS=emacs-snapshot
  global:
    - SOME_TOKEN=some_value

###
### allowing build failures
###

matrix:
  allow_failures:
#   - env: EMACS=xemacs21
    - env: EMACS=emacs-snapshot

###
### limit build attempts to defined branches
###
### notes
###
### This controls which branches are built.
###
### You can also control which branches affect the web badge, by
### appending "?branch=master,staging,production" to the end of the
### image URL (replacing "master,staging,production" with a
### comma-separated list of branches to be reflected in the badge).
###
#
#  branches:
#    only:
#      - master
#

###
### runtime initialization
###
### notes
###
### emacs22 is extracted manually from Ubuntu Maverick.
###
### emacs23 is the stock default, but is updated anyway to
### a GUI-capable version, which will have certain additional
### functions compiled in.
###
### emacs24 (current stable release) is obtained from the
### cassou PPA: http://launchpad.net/~cassou/+archive/emacs
###
### emacs-snapshot (trunk) is obtained from the Ubuntu Emacs Lisp PPA:
### https://launchpad.net/~ubuntu-elisp/+archive/ppa
### For the emacs-snapshot build, bleeding-edge versions
### of all test dependencies are also used.
###

before_install:
  - git submodule --quiet update --init --recursive

install:
  - if [ "$EMACS" = 'emacs25' ]; then
        sudo add-apt-repository -y ppa:kelleyk/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs25 emacs25-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs-snapshot &&
        sudo apt-get -qq install emacs-snapshot-el;
    fi

###
### the actual build/test command
###
### Use "make test-batch" to test without byte-compiling.
### The default command avoids byte-compiling on Emacs 22.
###

script:
  $EMACS --version && ( test "$EMACS" != 'emacs22' && EMACS="$EMACS" ./test/test.sh )

###
### settings
###

notifications:
  email: false

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
